### ISSUE TITLE
[Feature]: Invalid option tokenMint

### ISSUE THREAD

**Issue by alexmdcampo** [metaplex-foundation/candy-machine-ui#23]
### Feature

Error on use candy guards

Error: Invalid option tokenMint
    at OptionLayout.decode (index.ts:148:1)
    at Structure.decode (Layout.js:1234:1)
    at AccountsCoder.decode (accounts.ts:51:1)
    at AccountClient.fetchNullable (account.ts:143:1)
    at async AccountClient.fetch (account.ts:152:1)
    at async getProgramState (candy-machine.ts:178:1)
    at async Promise.all (:3000/index 0)
    at async getCandyMachineState (candy-machine.ts:187:1)
    at async Home.tsx:99:1

  "guards": {
    "default": {
      "mintLimit": {
        "id" : 1,
        "limit": 20
      },
      "startDate": {
        "date": "2022-10-23T20:00:00Z"
      }
    }
  }

### Ideal solution or implementation

.

### Other context

REACT_APP_CANDY_MACHINE_ID=DDnsCx2AmcPJVmc7qUcEPNz6HH4J6mbB4CeEzsRixc2f

**Comment by rivaslive** [comment]
Some problem for here! any solution?

**Comment by jaca420** [comment]
Same here! Just forked the project, added a valid machine id in .env and getting the same error.
